server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 45.153.245.177:8848
        username: nacos
        password: nacos
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
